name: Squash Merge PR
description: Squash merges a PR with custom commit message

inputs:
  commit-msg-file:
    description: 'Path to commit message file'
    required: false
    default: '/tmp/commit_msg.txt'
  pr-number:
    description: 'PR number to merge'
    required: true
  repository:
    description: 'Repository in owner/repo format'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: composite
  steps:
    - name: Post comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [[ ! -f "/tmp/comment.txt" ]]; then
          echo "::error::Comment file not found: /tmp/comment.txt"
          exit 1
        fi
        gh pr comment "${{ inputs.pr-number }}" --repo "${{ inputs.repository }}" --body-file /tmp/comment.txt

    - name: Check if merge should proceed
      id: check-merge
      shell: bash
      run: |
        if [[ -f "${{ inputs.commit-msg-file }}" ]]; then
          echo "should-merge=true" >> $GITHUB_OUTPUT
        else
          echo "should-merge=false" >> $GITHUB_OUTPUT
          echo "Tests failed. Skipping merge."
        fi

    - name: Validate commit message file
      if: steps.check-merge.outputs.should-merge == 'true'
      shell: bash
      run: |
        if [[ ! -f "${{ inputs.commit-msg-file }}" ]]; then
          echo "::error::Commit message file not found: ${{ inputs.commit-msg-file }}"
          exit 1
        fi

    - name: Squash merge
      if: steps.check-merge.outputs.should-merge == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        SUBJECT=$(head -1 "${{ inputs.commit-msg-file }}")
        BODY=$(tail -n +3 "${{ inputs.commit-msg-file }}")
        gh pr merge "${{ inputs.pr-number }}" --repo "${{ inputs.repository }}" --squash --subject "$SUBJECT" --body "$BODY"
