name: PR Start
description: Implements a GitHub issue and opens a PR

inputs:
  secrets-json:
    description: 'All secrets as JSON'
    required: true
  vars-json:
    description: 'All vars as JSON'
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/run-skill
      with:
        skill-name: pr-start
        context-type: issue
        fetch-depth: '0'
        secrets-json: ${{ inputs.secrets-json }}
        vars-json: ${{ inputs.vars-json }}

    - uses: ./.github/actions/git-commit-push
      with:
        branch-name-file: /tmp/pr_branch_name.txt
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
        bot-name: ${{ env.AGENTIC_BOT_NAME }}
        bot-email: ${{ env.AGENTIC_BOT_EMAIL }}

    - uses: ./.github/actions/create-pr
      with:
        issue-number: ${{ github.event.issue.number }}
        repository: ${{ github.repository }}
        github-token: ${{ env.AGENTIC_BOT_TOKEN }}
